package common

const (
	ContentType                   = "application/json"
	INTERNAL_SERVER_ERROR_MESSAGE = "internal server error"
	BAD_REQUEST_ERROR_MESSAGE     = "bad request error"
)

const (
	SERVER_PORT                       = "SERVER_PORT"
	SERVICE_EVENTING_TOOLS_BASE_URL_1 = "SERVICE_EVENTING_TOOLS_BASE_URL_1"
	SERVICE_EVENTING_TOOLS_BASE_URL_2 = "SERVICE_EVENTING_TOOLS_BASE_URL_2"
	SERVICE_EVENTING_TOOLS_BASE_URL_3 = "SERVICE_EVENTING_TOOLS_BASE_URL_3"
	SERVICE_EVENTING_TOOLS_BASE_URL_4 = "SERVICE_EVENTING_TOOLS_BASE_URL_4"
	SERVICE_EVENTING_TOOLS_BASE_URL_5 = "SERVICE_EVENTING_TOOLS_BASE_URL_5"
	SERVICE_EVENTING_TOOLS_ENDPOINT   = "SERVICE_EVENTING_TOOLS_ENDPOINT"
	SERVICE_DOWNSTREAM_BASE_URL       = "SERVICE_DOWNSTREAM_BASE_URL"
	SERVICE_DOWNSTREAM_ENDPOINT       = "SERVICE_DOWNSTREAM_ENDPOINT"
)
